# Generated by Django 4.0.3 on 2022-05-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_services',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
