# Generated by Django 4.0.3 on 2022-05-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_user_services_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_services',
            name='service_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='user_services',
            name='service_long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
