# Generated by Django 4.0.3 on 2022-05-31 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_user_services_service_lat_user_services_service_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_services',
            name='service_lat',
        ),
        migrations.RemoveField(
            model_name='user_services',
            name='service_long',
        ),
    ]
