# Generated by Django 4.0.3 on 2022-05-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_user_services_service_lat_user_services_service_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_services',
            name='service_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='user_services',
            name='service_long',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
