# Generated by Django 4.0.3 on 2022-05-31 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_user_services_service_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_services',
            name='service_lat',
        ),
        migrations.RemoveField(
            model_name='user_services',
            name='service_long',
        ),
    ]
