# Generated by Django 4.0.3 on 2022-05-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_user_services_service_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_services',
            name='service_lat',
            field=models.DecimalField(decimal_places=6, default=30.6988967, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_services',
            name='service_long',
            field=models.DecimalField(decimal_places=6, default=76.6918414, max_digits=9),
            preserve_default=False,
        ),
    ]
